### ISSUE TITLE
Simplify process of splitting input file by new lines

### ISSUE THREAD

**Issue by akrava** [FireAndBlood12/euro-diffusion#2]
In the code above we split by `\n` and after that do `map()` on each line in order to remove `\r`. I think it's not efficient. That's why I propose to split by regex with pattern `/\r?\n/`.

```suggestion
    .split(/\r?\n/);
```

https://github.com/FireAndBlood12/euro-diffusion/blob/db00827e2387681fc7588e22c017049a2ee49581/src/utils/parseInputFile.ts#L11-L12

_Originally posted by @akrava in https://github.com/FireAndBlood12/euro-diffusion/pull/1#discussion_r888247105_

**Comment by FireAndBlood12** [comment]
Thanks, fixed!
