### ISSUE TITLE
Extract `GridDictionary` class to the new file

### ISSUE THREAD

**Issue by akrava** [FireAndBlood12/euro-diffusion#3]
I think we need to move the class `GridDictionary` into separate file. Because it'll be more readable when in one file there is one class and it'll correspond OOP principles. Moreover, single class per file can solve problem of circular dependency, which can be in future.

https://github.com/FireAndBlood12/euro-diffusion/blob/db00827e2387681fc7588e22c017049a2ee49581/src/entities/map.ts#L6-L22

_Originally posted by @akrava in https://github.com/FireAndBlood12/euro-diffusion/pull/1#discussion_r888273975_

**Comment by FireAndBlood12** [comment]
Thanks, fixed!
