### ISSUE TITLE
Move magic numbers for country name max length into constants

### ISSUE THREAD

**Issue by akrava** [FireAndBlood12/euro-diffusion#4]
Let's create a constant for maximum county name length. Magic numbers are anti-pattern, it'll be hard to maintain in future.

https://github.com/FireAndBlood12/euro-diffusion/blob/db00827e2387681fc7588e22c017049a2ee49581/src/entities/country.ts#L20-L22

_Originally posted by @akrava in https://github.com/FireAndBlood12/euro-diffusion/pull/1#discussion_r888293782_

**Comment by FireAndBlood12** [comment]
Thanks, fixed!
