### ISSUE TITLE
Check if country string contains more than four coordinates

### ISSUE THREAD

**Issue by akrava** [FireAndBlood12/euro-diffusion#5]
There could be situation, when somebody can leave more than 4 numbers in country string. Now it's ignored, but I think we need to throw Exception because it's not a valid input.y

https://github.com/FireAndBlood12/euro-diffusion/blob/db00827e2387681fc7588e22c017049a2ee49581/src/entities/country.ts#L51

_Originally posted by @akrava in https://github.com/FireAndBlood12/euro-diffusion/pull/1#discussion_r888298006_

**Comment by FireAndBlood12** [comment]
Thanks, fixed!
