### ISSUE TITLE
Magic numbers for coins amount

### ISSUE THREAD

**Issue by akrava** [FireAndBlood12/euro-diffusion#6]
Let's replace magic numbers witch constants here also.

https://github.com/FireAndBlood12/euro-diffusion/blob/db00827e2387681fc7588e22c017049a2ee49581/src/entities/city.ts#L12-L13

_Originally posted by @akrava in https://github.com/FireAndBlood12/euro-diffusion/pull/1#discussion_r888307478_

**Comment by FireAndBlood12** [comment]
Thanks, fixed!
