### ISSUE TITLE
Sort countries with identical days to completion alphabetically by name

### ISSUE THREAD

**Issue by akrava** [FireAndBlood12/euro-diffusion#7]
The tasks says: 
> Order the countries by days to completion. If two countries have identical days to completion, order them alphabetically by name. 

I think we need to add here the logic of sorting results, which are printed to console.

https://github.com/FireAndBlood12/euro-diffusion/blob/db00827e2387681fc7588e22c017049a2ee49581/src/entities/map.ts#L152-L154

_Originally posted by @akrava in https://github.com/FireAndBlood12/euro-diffusion/pull/1#discussion_r888352336_

**Comment by FireAndBlood12** [comment]
Thanks, fixed!
